<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Color_Text</name>
   <tag></tag>
   <elementGuidId>91bf97da-1cb8-4f96-8bbe-b28faf5ebecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='option-label-color-93']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option-label-color-93</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9ebdce0-1e65-43c3-bf73-d002861825a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-color-93</value>
      <webElementGuid>b2a77d6f-1f9c-482c-8a6f-9c10723d6ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-attribute-label</value>
      <webElementGuid>6a1cad13-9f43-4f50-b123-700b146bd0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color</value>
      <webElementGuid>302452db-93e6-41b1-991e-9eb81f4def77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-color-93&quot;)</value>
      <webElementGuid>f44c9548-4bcc-43ef-aebd-1413ff975e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='option-label-color-93']</value>
      <webElementGuid>9a56d7af-fdb7-46c9-b62a-c67895b28842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div[2]/span</value>
      <webElementGuid>a4cdafa9-17c5-48ed-b61e-1a52f64bc6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/span</value>
      <webElementGuid>ca54e0f1-ea47-48d9-862c-f01fbc61a668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'option-label-color-93' and (text() = 'Color' or . = 'Color')]</value>
      <webElementGuid>73c25555-e9c5-4c72-a24e-93023358864b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
