<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price_Text</name>
   <tag></tag>
   <elementGuidId>d39952fa-c25f-4f36-bc5f-87254621f6ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product-price-1316']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ad7c104-ee77-47b7-9bc0-343d20dbb0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>7428c034-7f26-4f58-8364-20f2b14ac941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$57.00</value>
      <webElementGuid>d246767c-7283-4a2f-963a-a75731f7ee1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-price-1316&quot;)/span[@class=&quot;price&quot;]</value>
      <webElementGuid>7348082d-d6d6-492e-a6f4-93e602c3aca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='product-price-1316']/span</value>
      <webElementGuid>369756e9-8075-43c9-9968-f3301c342535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/span</value>
      <webElementGuid>c4812a1f-ccca-4e6c-8617-23def5191359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$57.00' or . = '$57.00')]</value>
      <webElementGuid>d3f864cc-f3b5-4303-ac77-012ab2f66934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
