<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quantity_Text</name>
   <tag></tag>
   <elementGuidId>9a6e6bc1-5372-4488-8dfd-f7452d33266e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product_addtocart_form']/div[2]/div/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.field.qty > label.label > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e730e637-b3fb-41bf-8507-4582ab76a0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>6d739902-f26b-474b-8db1-527d12a9a300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_addtocart_form&quot;)/div[@class=&quot;product-options-bottom&quot;]/div[@class=&quot;box-tocart&quot;]/div[@class=&quot;fieldset&quot;]/div[@class=&quot;field qty&quot;]/label[@class=&quot;label&quot;]/span[1]</value>
      <webElementGuid>0c3c8f6f-0381-4589-b4c0-ec5b1b0593cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/div/div/label/span</value>
      <webElementGuid>4fad51d7-ecf1-4cd0-8f06-83fa840afd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/span</value>
      <webElementGuid>135704bb-a714-4b01-b7e0-e07eb7702057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qty' or . = 'Qty')]</value>
      <webElementGuid>d22c1333-621d-408a-9450-8ede3904ddd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
