<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Size_Text</name>
   <tag></tag>
   <elementGuidId>c52f8d79-65a8-42b3-bd04-f69a7b2969f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='option-label-size-143']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option-label-size-143</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb3f04b8-e143-4718-8a06-481b2604fc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-143</value>
      <webElementGuid>da9f8d96-5aea-4f6a-a77d-8f30e11dc9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-attribute-label</value>
      <webElementGuid>d724a84c-3a81-46fd-97ed-77cabbba9d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>5c663698-8916-4c8a-a149-c2d5a18070a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-size-143&quot;)</value>
      <webElementGuid>39d816a4-9f94-40e0-807a-908089d48d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='option-label-size-143']</value>
      <webElementGuid>881b51bc-3af3-4c2c-95a4-4df06a303dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/span</value>
      <webElementGuid>8dee8262-ab2f-42b1-a04b-43e0ea62aefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/span</value>
      <webElementGuid>9f36ac68-6882-4bc3-bfbf-ad477b19d5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'option-label-size-143' and (text() = 'Size' or . = 'Size')]</value>
      <webElementGuid>dd74154e-d436-4548-ac52-666f46a07954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
