<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stock_Status_Text</name>
   <tag></tag>
   <elementGuidId>d0071400-8659-4153-bc90-7398219911ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[2]/div[3]/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.stock.available > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dab403bb-c1c4-4523-8482-13f0ac787af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In stock</value>
      <webElementGuid>3eba893e-e88e-4899-8bbc-6c449ab1fb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product-info-main&quot;]/div[@class=&quot;product-info-price&quot;]/div[@class=&quot;product-info-stock-sku&quot;]/div[@class=&quot;stock available&quot;]/span[1]</value>
      <webElementGuid>e893f411-511c-4fd7-b426-ae693e129804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[2]/div[3]/div[2]/div/span</value>
      <webElementGuid>e277ab81-5c37-4a26-8537-0e40f2fbcd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>654d58c8-53bb-44a8-a15e-c5f0149ce5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'In stock' or . = 'In stock')]</value>
      <webElementGuid>a2c844c9-757b-445f-9405-9904082b3a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
