<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Color_Text</name>
   <tag></tag>
   <elementGuidId>93b7fe6d-4cb4-4f4a-9d39-c76a2006341c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dt[text()=&quot;Color&quot;]/following::span[text()=&quot;Orange&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
