<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Size_Text</name>
   <tag></tag>
   <elementGuidId>a2b0000f-d69b-40b9-82bb-3153e031c3cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dt[text()=&quot;Size&quot;]/following::span[text()=&quot;XS&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
